### ISSUE TITLE
$expires not working 

### ISSUE THREAD

**Issue by Lucifer1903** [jagerman/loki-sn-bot#2]
No response from LokiSNBot when $expires is entered.

Maybe due to the amount of SNs monitored by LokiSNBot. Could an account with large amount of SNs cause this?

**Comment by Lucifer1903** [comment]
It seems to not work when nodes are in the 15 day unlock period. When they are infinite staked or deregistered there is a response from LokiSNBot.

**Comment by jagerman** [comment]
I've having trouble reproducing this.  Is it still happening?

**Comment by jagerman** [comment]
Ah, yes, I think the issue is this:

> Could an account with large amount of SNs cause this?

when the reply gets over 2000 characters Discord returns an error.  I'll split up long messages.

**Comment by jagerman** [comment]
Should be fixed by 806c44be192cfa9b1cb222a36de7229f2617ce25
