### ISSUE TITLE
$norewards is broken

### ISSUE THREAD

**Issue by 1point21gigabytes** [jagerman/loki-sn-bot#4]
The `$norewards` command isn't working at the moment.  I tried `$norewards 1` and `$norewards <pubkey>`; neither command was successful.  And doing `$sn 1` afterwards showed that reward notifications were still enabled.

**Comment by 1point21gigabytes** [comment]
To clarify, by "not successful" I mean there was no response from the bot whatsoever.  Not even an error message.

**Comment by 1point21gigabytes** [comment]
Oh, and this is regarding the Discord version of the bot.

**Comment by jagerman** [comment]
Thanks for the report, should be fixed now.
